services:
  python:
    container_name: python-docker-container
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/opt/mnt
    ports:
      - 8888:8888
    tty: true